### ISSUE TITLE
Добавить вывод статистики по поиску на графе

### ISSUE THREAD

**Issue by aurusov** [kstrizhov/rdo-xtext#2]
Подсмотреть в новой лабе по пятнашкам.

**Comment by kstrizhov** [comment]
Добавил вывод статистики по поиску, сейчас это выглядит вот так.

![2014-12-15 23 03 51](https://cloud.githubusercontent.com/assets/9355661/5443098/0984a840-84b0-11e4-8700-e83e4d6c6d5e.png)

**Comment by aurusov** [comment]
Выглядит хорошо.
