### ISSUE TITLE
Изменить расцветку найденного решения

### ISSUE THREAD

**Issue by aurusov** [kstrizhov/rdo-xtext#3]
Не видно текста

**Comment by kstrizhov** [comment]
![2014-12-13 00 10 07](https://cloud.githubusercontent.com/assets/9355661/5419435/b5984cfa-825c-11e4-8fce-0642f5f7193e.png)

Как насчет такого варианта?

**Comment by aurusov** [comment]
Да

**Comment by aurusov** [comment]
Переоткрыто из-за https://github.com/kstrizhov/rdo-xtext/commit/fb61c910871d831596dc0baadaf7c17eebba3b4f#commitcomment-8958787

**Comment by kstrizhov** [comment]
Сделано.
