### ISSUE TITLE
Стротить граф для каждой точки

### ISSUE THREAD

**Issue by aurusov** [kstrizhov/rdo-xtext#5]
В трассировке может быть несколько точек типа `search`. Надо уметь не только определять для какой именно строиться граф (#4), но и выводить каждый краф в отдельном окне. При повторном клике на трассироку надо открывать уже созданный граф.

**Comment by kstrizhov** [comment]
Теперь по нажатию кнопки `Build Graph` открываются окошки с графами для всех точек принятия решений.

Выглядит примерно так.

![2014-12-17 17 42 57](https://cloud.githubusercontent.com/assets/9355661/5472885/28fb9686-8616-11e4-8b72-44bde3d7ecbc.png)

**Comment by aurusov** [comment]
Где эта кнопка расположена ? Что будет, если жмакнуть по ней второй раз ?

**Comment by kstrizhov** [comment]
Это дебажная кнопка `Build Graph` в меню. Мы обсуждали, что она временная и ее надо убрать.
Вызов графов по ней был сделан для проверки возможности строить графы в отдельных окнах для каждой точки принятия решений.

Если нажать кнопку еще раз, снова вызовется два окна. Сейчас думаю над тем, как это дело исправить.

**Comment by aurusov** [comment]
> Если нажать кнопку еще раз, снова вызовется два окна. Сейчас думаю над тем, как это дело исправить.

Зачем думать, если кнопка уйдёт ? Лучше сразу пилить продуктовое решение с кликом по трассировке. А еще лучше отложить и делать листы.
