### ISSUE TITLE
Интерактивность графа

### ISSUE THREAD

**Issue by kstrizhov** [kstrizhov/rdo-xtext#6]
Убрать всю интерактивность, кроме возможности передвигать вершины.

**Comment by kstrizhov** [comment]
@aurusov 

Добавил возможность двигать вершины, рисовать по-прежнему нельзя. Но почему в консоль сыпятся ошибки, если передвинуть какую-либо вершину. На работоспособность не влияет.
![2014-12-15 14 39 12](https://cloud.githubusercontent.com/assets/9355661/5435595/7ab83312-846d-11e4-9248-d5c32b409ba8.png)
![2014-12-15 14 39 23](https://cloud.githubusercontent.com/assets/9355661/5435596/7d8043be-846d-11e4-90a0-ca726cfce107.png)

**Comment by aurusov** [comment]
Скрины мало помогают, надо выкладывать стек. А еще лучше самому прочитать сообщение на вершине стека и подумать почему.

**Comment by kstrizhov** [comment]
Он для каждой подвинутой вершины выдает ошибку, которая есть на скрине: Drag and drop in progress.

Скрин для одной из вершин.

**Comment by aurusov** [comment]
Что говорит гугл ?
