### ISSUE TITLE
Вывод статистики при выделении вершины кликом

### ISSUE THREAD

**Issue by kstrizhov** [kstrizhov/rdo-xtext#7]
@aurusov 

Обсудили с @bogachev-pa, подумали что было бы неплохо реализовать вывод окошка с подробной статистикой по выделении вершины графа кликом, возможно по фиче можно будет сделать лист с диаграммой состояний. Сделал, вот варианты того, что получилось.

Окошко со статистикой по вершине под окошком со статистикой по графу.
![2015-01-18 00 28 32](https://cloud.githubusercontent.com/assets/9355661/5790453/d8af498c-9ea9-11e4-91c5-0fc978c73940.png)

Окошко со статистикой с другой стороны.
![2015-01-18 00 25 14](https://cloud.githubusercontent.com/assets/9355661/5790457/2813e406-9eaa-11e4-8b33-51e786d260ba.png)

При выделении нескольких вершин подряд статистика обновляется (перерисовывается окошко)

**Comment by aurusov** [comment]
Выглядит хорошо. Я за второй вариант дизайна.

> При выделении нескольких вершин...

Не понял

**Comment by kstrizhov** [comment]
Я про то, что если прокликивать разные вершины, статистика обновляется. На картинках не показать, но вроде достаточно юзабельно все получилось. Тогда оставляю второй вариант.

**Comment by aurusov** [comment]
Понял. Хорошо.

**Comment by kstrizhov** [comment]
Появился вопрос, стоит ли в выводимой статистике по вершине указывать принадлежность к решению? Или это будет дублирование информации, потому что и так помечено другим цветом?

**Comment by aurusov** [comment]
Дублирование, не надо.

Советую (в который раз ?) забросить код и заняться оформлением курсового.

**Comment by kstrizhov** [comment]
Да в код одну строчку добавить. Вопрос и возник по ходу его оформления.

**Comment by aurusov** [comment]
Дело не объеме работ (тоже важно, конечно), а во внимании. Оно у тебя одно imho. А смена контекста может быть долгой (15 минут, к примеру). А вот последняя фраза порадовала.
