### ISSUE TITLE
Работа в режиме процесса моделирования

### ISSUE THREAD

**Issue by kstrizhov** [kstrizhov/rdo-xtext#9]
Необходимо реализовать возможность построения новых вершин "на лету", по мере добавления новых записей в базу данных. 

Привязать к шкале масштабирования времени моделирования.

**Comment by kstrizhov** [comment]
@aurusov 
@k-alexandrovsky

Сделал обновление графа в процессе поиска, но почему -то некоторые вершины рисуются без связей с предками, а потом в дальнейшем между такими вершинами появляются какие-то непонятные связи, будто бы он позднее определил кто для кого потомок\предок. В итоге рисует пока ерунду. 

По идее каждая новая запись после того, как ее распарсили, добавляет в дерево новую вершину, и у нее обязательно должен быть предок, то есть граф всегда связный во время процесса поиска. Грешу либо на свой метод отрисовки и способ хранения последней добавленной вершины, либо я чего-то не учитываю в алгоритме поиска.

**Comment by kstrizhov** [comment]
Посмотрел номера вершин, которые поподают в функцию отрисовки, они почему-то идут через одну, такое ощущение, что сериализуются быстрее, чем происходит обновление графа.

![2015-02-19 01 05 38](https://cloud.githubusercontent.com/assets/9355661/6257699/8bfd6216-b7d3-11e4-80eb-4d907d404bab.png)

Менял скорость обновления [здесь](https://github.com/kstrizhov/rdo-xtext/blob/test_branch/ru.bmstu.rk9.rdo.lib/src/ru/bmstu/rk9/rdo/lib/GraphControl.java#L39), повлияло вот таким образом.
![2015-02-19 01 19 07](https://cloud.githubusercontent.com/assets/9355661/6257948/5b27d8ea-b7d5-11e4-82bb-d8c4ce5e0382.png)

Пока думаю, как это исправить.

**Comment by aurusov** [comment]
Выглядит так, что контейнер вершин не под мьютексом. Со стороны сериализатора ему нужен write_lock. Со стороны графа - read_lock.

**Comment by aurusov** [comment]
Граф строится в режиме реального времени.
Есть ошибка - найденный путь заполняется, но не отрисовывается заданным стилем.

**Comment by kstrizhov** [comment]
@aurusov, мы обсуждали на консультации, что у меня в конструкторе есть копипаста (в теле конструктора и в `TimerTask`е), которую надо убрать. Может на консультации уже был глаз замылен, и я не обратил на это ваше внимание, но у меня в первом случае вызывается метод `drawGraph()`, а во втором `drawNewVertex()`. И это все обернуто в стандартную конструкцию

``` java
graph.getModel().beginUpdate();
try {
//преобразования с графом
} finally {
graph.getModel().endUpdate();
}
```

Я вижу смысл только в идее вынести вообще все в метод, чтобы вызывать пустой конструктор, а рисовать все после прогона, дергая его в другом месте. С копипастой остался вопрос.

**Comment by aurusov** [comment]
> Я вижу смысл только в идее вынести вообще все в метод, чтобы вызывать пустой конструктор, а рисовать все после прогона, дергая его в другом месте. 

Да, так и договаривались

> С копипастой остался вопрос.

В чем разница в коде между методами ?

**Comment by kstrizhov** [comment]
`drawGraph` строит дерево со всеми вершинами, отсериализованными из БД на момент вызова, вызывается один раз при создании окна, `drawNewVertex` по таймеру отрисовывает разницу между отсериализованными вершинами и отображенными на экране.

**Comment by aurusov** [comment]
Переименуй их, чтобы по названию было понятно.

**Comment by kstrizhov** [comment]
Исправил, все работает.

**Comment by aurusov** [comment]
Отлично. Ошибка очень обидная, думал, что перерисовка окна вызывает этот метод. Закрывай таску.
